KEYMAP_SETTINGS = [
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "3D View",
        "letter": "A",
        "idname": "PIE_MT_AddMesh",
        "shift": 1,
        "ctrl": 0,
        "alt": 0,
        "space_type": "VIEW_3D",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Mesh",
        "letter": "A",
        "idname": "PIE_MT_AddMesh",
        "shift": 1,
        "ctrl": 0,
        "alt": 0,
        "space_type": "VIEW_3D",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "3D View",
        "letter": "A",
        "idname": "PIE_MT_AddOtherObjects",
        "shift": 1,
        "ctrl": 1,
        "alt": 0,
        "space_type": "VIEW_3D",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Mesh",
        "letter": "X",
        "idname": "mesh.reduce_cylinder",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "VIEW_3D",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "3D View Generic",
        "letter": "Q",
        "idname": "PIE_MT_AddModifier",
        "shift": 1,
        "ctrl": 1,
        "alt": 0,
        "space_type": "VIEW_3D",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Object Mode",
        "letter": "C",
        "idname": "PIE_MT_ConvertMeshCurve",
        "shift": 0,
        "ctrl": 0,
        "alt": 1,
        "space_type": "VIEW_3D",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Node Editor",
        "letter": "W",
        "idname": "NODE_OT_node_align_top",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Node Editor",
        "letter": "S",
        "idname": "NODE_OT_node_align_bottom",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Node Editor",
        "letter": "D",
        "idname": "NODE_OT_node_align_right",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
        "region_type": "WINDOW",
    },
    {
        "keymap_operator": "wm.call_menu_pie",
        "name": "Node Editor",
        "letter": "A",
        "idname": "NODE_OT_node_align_left",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
        "region_type": "WINDOW",
    },
]
