KEYMAP_SETTINGS = [
    {
        'name': "3D View",
        'letter': "A",
        'class': "PIE_MT_AddMesh",
        "shift": 1,
        "ctrl": 0,
        "alt": 0,
        "space_type": "VIEW_3D",
    },
    {
        'name': "3D View",
        'letter': "ACCENT_GRAVE",
        'class': "PIE_MT_SnapOptions",
        "shift": 0,
        "ctrl": 1,
        "alt": 1,
        "space_type": "VIEW_3D",
    },
    {
        'name': "Mesh",
        'letter': "ACCENT_GRAVE",
        'class': "PIE_MT_SnapOptions",
        "shift": 0,
        "ctrl": 1,
        "alt": 1,
        "space_type": "VIEW_3D",
    },
    {
        'name': "Mesh",
        'letter': "A",
        'class': "PIE_MT_AddMesh",
        "shift": 1,
        "ctrl": 0,
        "alt": 0,
        "space_type": "VIEW_3D",
    },
    {
        'name': "3D View",
        'letter': "A",
        'class': "PIE_MT_AddOtherObjects",
        "shift": 1,
        "ctrl": 1,
        "alt": 0,
        "space_type": "VIEW_3D",
    },
    # Reduce Cylinder Edges
    {
        'name': "Mesh",
        'letter': "X",
        'class': "mesh.reduce_cylinder",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "VIEW_3D",
    },
    {
        'name': "3D View",
        'letter': "Q",
        'class': "PIE_MT_AddModifier",
        "shift": 1,
        "ctrl": 1,
        "alt": 0,
        "space_type": "VIEW_3D",
    },
    {
        'name': "Object Mode",
        'letter': "C",
        'class': "PIE_MT_ConvertMeshCurve",
        "shift": 0,
        "ctrl": 0,
        "alt": 1,
        "space_type": "VIEW_3D",
    },
    {
        'name': "Node Editor",
        'letter': "W",
        'class': "NODE_OT_node_align_top",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
    },
    {
        'name': "Node Editor",
        'letter': "S",
        'class': "NODE_OT_node_align_bottom",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
    },
    {
        'name': "Node Editor",
        'letter': "D",
        'class': "NODE_OT_node_align_right",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
    },
    {
        'name': "Node Editor",
        'letter': "A",
        'class': "NODE_OT_node_align_left",
        "shift": 1,
        "ctrl": 0,
        "alt": 1,
        "space_type": "NODE_EDITOR",
    },
]
